[package]
name = "handle_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tracing = {version = "0.1.40",features = ["log"]}
reqwest = {version = "0.11",features = ["json"]}
reqwest-middleware = "0.1.1" 