[workspace]
members = [
    "rust_course",
    "exercism",
    "flappy_dragon",
    "treehouse",
    "dungeon_crawl",
    "dungeon_crawl_ecs",
    "melee_combat",
    "what_can_i_see",
    "more_instresting_dungeons",
    "inventory_and_power_ups",
    "deeper_dungeons"
]
